# Generated by Django 5.0 on 2024-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_moodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicompanion',
            name='avatar_base',
            field=models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('hexagon', 'Hexagon')], default='circle', max_length=20),
        ),
        migrations.AddField(
            model_name='aicompanion',
            name='avatar_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('orange', 'Orange')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='aicompanion',
            name='avatar_decoration',
            field=models.CharField(choices=[('none', 'None'), ('glasses', 'Glasses'), ('bowtie', 'Bow Tie'), ('flower', 'Flower'), ('hat', 'Hat'), ('crown', 'Crown')], default='none', max_length=20),
        ),
    ]
