# Generated by Django 5.0 on 2024-12-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_therapist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
