# Generated by Django 5.0 on 2024-12-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
