# Generated by Django 5.0 on 2024-12-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='struggling_with',
            field=models.CharField(blank=True, choices=[('anxiety', 'Anxiety'), ('stress', 'Stress'), ('sleep', 'Sleep'), ('depression', 'Depression'), ('selfcare', 'Self Care')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AICompanion',
        ),
    ]
