# Generated by Django 5.0 on 2024-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
