# Generated by Django 5.0 on 2024-12-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_chatsession_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='analysis_text',
            new_name='ai_analysis',
        ),
        migrations.AddField(
            model_name='report',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
