# Generated by Django 5.0 on 2024-12-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_analysis_text_report_ai_analysis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='ai_analysis',
            new_name='analysis_text',
        ),
        migrations.RemoveField(
            model_name='report',
            name='analysis_data',
        ),
    ]
