# Generated by Django 5.0 on 2024-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_ai_analysis_report_analysis_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='analysis_text',
        ),
        migrations.AddField(
            model_name='report',
            name='analysis',
            field=models.TextField(blank=True),
        ),
    ]
